<?php

/**
 * BaseForum
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $message
 * 
 * @method string getMessage() Returns the current record's "message" value
 * @method Forum  setMessage() Sets the current record's "message" value
 * 
 * @package    forum
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseForum extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('forum');
        $this->hasColumn('message', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}