<?php

/**
 * ForumMessageTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ForumMessageTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ForumMessageTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('ForumMessage');
    }
    
    public function getAllMessages() {
        $query = Doctrine_Query::create()
                    ->select('message')
                    ->from('ForumMessage m')
                    ->orderBy('m.created_at', 'ASC');
        return $query->execute();
    }
}